---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: web
    spec:
      initContainers:
      - name: wait-for-backend
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for backend to be ready..."
          until nc -z backend 8080; do
            echo "Backend is not ready yet. Waiting..."
            sleep 5
          done
          echo "Backend is ready! Starting frontend..."
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - name: frontend
        image: quay.io/rh-aiservices-bu/litemaas-frontend:0.0.7
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: BACKEND_URL
          value: "http://backend:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
