---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  labels:
    app: litellm
    component: ai-proxy
type: Opaque
stringData:
  database-url: <DATABASE_URL>
  master-key: <MASTER_KEY>
  ui-password: <UI_PASSWORD>
  ui-username: <UI_USERNAME>
